import { ChevronLeft, ChevronRight } from 'lucide-react'
import { UserAvatar } from '../Users/UserDetails.jsx'
import { LFGStatus } from './LFGDetails.jsx'
import { sportLabels, date, number } from './lfgData.js'

export default function LFGTable({ activities, detailId, onDetail, page, pageSize, onPage, onPageSize }) {
  const pages = Math.max(1, Math.ceil(activities.length / pageSize)), currentPage = Math.min(page, pages)
  const visible = activities.slice((currentPage - 1) * pageSize, currentPage * pageSize)
  return <section className="lfg-table-panel" aria-label="Danh sách kèo ghép trận"><header><h2>Danh sách kèo ghép trận <span>{number(activities.length)} kèo mẫu</span></h2><small>● Dữ liệu trong phiên</small></header><div className="lfg-table-scroll"><table><thead><tr>{['Mã kèo / tiêu đề', 'Môn thể thao', 'Người tổ chức', 'Cơ sở / sân', 'Ngày / giờ', 'Trạng thái'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{visible.map(activity => <tr key={activity.id} className={detailId === activity.id ? 'is-selected' : ''} onClick={() => onDetail(activity.id)}><td><button className="lfg-title-button" onClick={() => onDetail(activity.id)} aria-expanded={detailId === activity.id}><strong>{activity.title}</strong><small>#{activity.id}</small>{activity.reports.length > 0 && <span>{activity.reports.length} báo cáo</span>}</button></td><td><span className={`lfg-sport ${activity.venue.sport.toLowerCase()}`}>{sportLabels[activity.venue.sport]}</span></td><td><div className="lfg-table-host"><UserAvatar user={activity.host} /><strong>{activity.host.name}</strong></div></td><td><strong>{activity.venue.name}</strong><small>{activity.venue.court}</small></td><td>{date(activity.date)}<small>{activity.start} – {activity.end}</small></td><td><LFGStatus status={activity.status} /></td></tr>)}</tbody></table>{!visible.length && <p className="lfg-empty">Không có kèo phù hợp. Hãy điều chỉnh hoặc đặt lại bộ lọc.</p>}</div><footer className="lfg-pagination"><span>Hiển thị {activities.length ? number((currentPage - 1) * pageSize + 1) : 0}–{number(Math.min(currentPage * pageSize, activities.length))} / {number(activities.length)} kèo mẫu</span><label>Số dòng mỗi trang<select value={pageSize} onChange={event => onPageSize(Number(event.target.value))}>{[5, 10, 15].map(size => <option key={size} value={size}>{size} dòng</option>)}</select></label><nav aria-label="Phân trang kèo ghép trận"><button aria-label="Trang trước" disabled={currentPage === 1} onClick={() => onPage(currentPage - 1)}><ChevronLeft size={13} /></button>{Array.from({ length: pages }, (_, index) => index + 1).map(value => <button key={value} aria-label={`Trang ${value}`} aria-current={currentPage === value ? 'page' : undefined} onClick={() => onPage(value)}>{value}</button>)}<button aria-label="Trang sau" disabled={currentPage === pages} onClick={() => onPage(currentPage + 1)}><ChevronRight size={13} /></button></nav></footer></section>
}
