import { useNavigate } from 'react-router-dom'

function AIChatBooking() {
  const navigate = useNavigate()

  return (
    <div className="flex flex-col w-full h-[calc(100vh-4rem)] max-w-5xl mx-auto px-margin py-space-md">
      {/* Header */}
      <div className="flex items-center justify-between p-space-md bg-surface-container-low rounded-t-2xl border-b border-outline-variant/20">
        <div className="flex items-center gap-space-sm">
          <div className="w-10 h-10 rounded-xl bg-primary-container/20 flex items-center justify-center text-primary">
            <span className="material-symbols-outlined text-[24px]">smart_toy</span>
          </div>
          <div>
            <h1 className="font-headline-sm text-headline-sm text-on-surface font-bold">Kinetic AI Concierge</h1>
            <span className="font-label-sm text-label-sm text-on-surface-variant flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-secondary-fixed animate-pulse"></span> Online • Natural Language Booking
            </span>
          </div>
        </div>
      </div>

      {/* Chat History */}
      <div className="flex-1 overflow-y-auto bg-surface-container-lowest p-space-lg flex flex-col gap-space-lg">
        {/* Date Divider */}
        <div className="flex items-center justify-center">
          <span className="px-3 py-1 rounded-full bg-surface-container text-on-surface-variant font-label-sm text-label-sm">Today, 14:30</span>
        </div>

        {/* User Message */}
        <div className="flex flex-col items-end gap-1">
          <div className="px-4 py-2.5 rounded-2xl rounded-tr-sm bg-surface-container-high text-on-surface max-w-[80%]">
            <p className="font-body-md text-body-md">Find me a badminton court tonight around 19:00 for 4 players. Somewhere in the downtown area.</p>
          </div>
        </div>

        {/* AI Response with Card */}
        <div className="flex flex-col items-start gap-2 max-w-[90%]">
          <div className="flex items-center gap-2 mb-1">
            <span className="material-symbols-outlined text-primary text-[18px]">smart_toy</span>
            <span className="font-label-sm text-label-sm text-primary uppercase font-bold">Kinetic AI</span>
          </div>
          
          <div className="px-4 py-2.5 rounded-2xl rounded-tl-sm bg-surface-container-low text-on-surface">
            <p className="font-body-md text-body-md">I found a few options for you. The best match is at Kinetic Arena Metro which has a Pro-Mat court available exactly at 19:00.</p>
          </div>

          {/* Interactive Court Card generated by AI */}
          <div className="mt-2 w-full max-w-sm rounded-xl bg-surface-container border border-outline-variant/30 overflow-hidden shadow-lg">
            <img className="w-full h-32 object-cover" src="https://lh3.googleusercontent.com/aida/AEtjO1WdQ1-KKfnvwaSO4limEZmMa4EYvWiwHJh-ee9W3R9MusGMY2e0qlgwXbsjqxoztcUlkiHxzOLU8Rj7fuDxe23FEJagcAhTZzSXyAJNqkf5YUHNbGPgjZPKwuCCO3EoHymYunbwsdWb_O_Z2P3Oj4yT_rItFinuMCXFEQB0i1oR2ufaSKbZ8FxN1mCuYZFgWIDhw1Yxoh1z054PmkESyxdccl2X-cYwTGBP4Oxk-GIVOkLs9bC3tbWYLg" alt="Court" />
            <div className="p-space-md flex flex-col gap-space-sm">
              <div>
                <h3 className="font-headline-sm text-headline-sm text-on-surface font-bold">Kinetic Arena Metro</h3>
                <span className="font-body-sm text-body-sm text-on-surface-variant flex items-center gap-1">
                  <span className="material-symbols-outlined text-[14px] text-primary">location_on</span> 2.5 km away
                </span>
              </div>
              <div className="flex items-center justify-between p-2 rounded-lg bg-surface-container-highest">
                <span className="font-label-md text-label-md text-on-surface font-bold">19:00 - 20:00</span>
                <span className="font-headline-sm text-headline-sm text-secondary-fixed font-bold">$18.00</span>
              </div>
              <button className="w-full py-2 rounded-lg bg-primary-container text-on-primary-container font-label-md text-label-md font-bold flex items-center justify-center gap-1 shadow-md hover:brightness-110 transition-all" onClick={() => navigate('/court')}>
                <span>View Details</span>
                <span className="material-symbols-outlined text-[18px]">arrow_forward</span>
              </button>
            </div>
          </div>
          
          <div className="flex flex-wrap gap-2 mt-2">
            <button className="px-3 py-1.5 rounded-full bg-surface-container-high border border-outline-variant/30 text-primary font-label-sm text-label-sm hover:bg-surface-bright transition-colors">Book this one</button>
            <button className="px-3 py-1.5 rounded-full bg-surface-container-high border border-outline-variant/30 text-on-surface font-label-sm text-label-sm hover:bg-surface-bright transition-colors">Show more options</button>
            <button className="px-3 py-1.5 rounded-full bg-surface-container-high border border-outline-variant/30 text-on-surface font-label-sm text-label-sm hover:bg-surface-bright transition-colors">Change time to 20:00</button>
          </div>
        </div>
      </div>

      {/* Input Area */}
      <div className="p-space-md bg-surface-container-low rounded-b-2xl border-t border-outline-variant/20">
        <div className="flex items-center gap-space-sm bg-surface-container-lowest p-2 rounded-xl border border-outline-variant/30 focus-within:border-primary focus-within:shadow-[0_0_10px_rgba(0,229,255,0.2)] transition-all">
          <button className="p-2 text-on-surface-variant hover:text-primary transition-colors">
            <span className="material-symbols-outlined text-[20px]">add_circle</span>
          </button>
          <input className="flex-1 bg-transparent border-none outline-none font-body-md text-body-md text-on-surface placeholder:text-on-surface-variant" placeholder="Ask AI to book, invite players, or find matches..." type="text" />
          <button className="p-2 text-on-surface-variant hover:text-primary transition-colors">
            <span className="material-symbols-outlined text-[20px]">mic</span>
          </button>
          <button className="p-2 rounded-lg bg-primary-container text-on-primary-container hover:brightness-110 shadow-[0_0_10px_rgba(0,229,255,0.3)] transition-all flex items-center justify-center">
            <span className="material-symbols-outlined text-[18px]">send</span>
          </button>
        </div>
      </div>
    </div>
  )
}

export default AIChatBooking
