import { ChevronLeft, ChevronRight } from 'lucide-react'
import { RegistrationProgress, TournamentStatus } from './TournamentDetails.jsx'
import { sportLabels, date, number } from './tournamentData.js'

export default function TournamentTable({ tournaments, detailId, onDetail, page, pageSize, onPage, onPageSize }) {
  const pages = Math.max(1, Math.ceil(tournaments.length / pageSize)), current = Math.min(page, pages)
  const visible = tournaments.slice((current - 1) * pageSize, current * pageSize)
  return <section className="tournaments-table-panel" aria-label="Danh sách giải đấu"><header><h2>Danh sách giải đấu</h2><small>Dữ liệu minh họa trong phiên</small></header><div className="tournaments-table-scroll"><table><thead><tr>{['Giải đấu', 'Môn thể thao', 'Cơ sở', 'Ngày', 'Đăng ký', 'Trạng thái'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{visible.map(t => <tr key={t.id} className={detailId === t.id ? 'is-selected' : ''} onClick={() => onDetail(t.id)}><td><button className="tournaments-title-button" onClick={() => onDetail(t.id)} aria-expanded={detailId === t.id}><strong>{t.name}</strong><small>#{t.id}</small></button></td><td><span className={`tournaments-sport ${t.sport.toLowerCase()}`}>{sportLabels[t.sport]}</span></td><td>{t.facility}</td><td>{date(t.starts)}<small>đến {date(t.ends)}</small></td><td><RegistrationProgress tournament={t} /></td><td><TournamentStatus status={t.status} /></td></tr>)}</tbody></table>{!visible.length && <p className="tournaments-empty">Không có giải phù hợp. Hãy điều chỉnh hoặc đặt lại bộ lọc.</p>}</div><footer className="tournaments-pagination"><span>Hiển thị {tournaments.length ? number((current - 1) * pageSize + 1) : 0}–{number(Math.min(current * pageSize, tournaments.length))} / {number(tournaments.length)} giải mẫu</span><label>Số dòng mỗi trang<select value={pageSize} onChange={event => onPageSize(Number(event.target.value))}>{[5, 10, 15].map(size => <option key={size} value={size}>{size} dòng</option>)}</select></label><nav aria-label="Phân trang giải đấu"><button aria-label="Trang trước" disabled={current === 1} onClick={() => onPage(current - 1)}><ChevronLeft size={13} /></button>{Array.from({ length: pages }, (_, index) => index + 1).map(value => <button key={value} aria-label={`Trang ${value}`} aria-current={value === current ? 'page' : undefined} onClick={() => onPage(value)}>{value}</button>)}<button aria-label="Trang sau" disabled={current === pages} onClick={() => onPage(current + 1)}><ChevronRight size={13} /></button></nav></footer></section>
}
