import { useState } from 'react'
import { DemoDialog } from '../Users/UserDialogs.jsx'
import { UserAvatar } from '../Users/UserDetails.jsx'
import { SplitSummary } from './TransactionDetails.jsx'
import { money, date, methodLabels } from './paymentData.js'

export default function PaymentDialogs({ dialog, onClose, onSaveReview }) {
  const t = dialog.transaction
  const [note, setNote] = useState(t?.issue?.note || '')
  const [reviewed, setReviewed] = useState(t?.issue?.reviewed || false)
  const [error, setError] = useState('')
  if (dialog.type === 'security') return <DemoDialog title="Thông tin bảo vệ ký quỹ — Bản mẫu" closeLabel="Đóng hộp thoại" onClose={onClose}><p>Giao diện minh họa cách theo dõi tiền đóng góp theo nhóm và trạng thái ký quỹ. Quản trị viên chỉ xem thông tin và ghi chú rà soát.</p><p className="users-demo-note">Trang chưa kết nối hệ thống thanh toán. Không có tiền thật được giữ, giải ngân, chuyển hoặc hoàn trả qua các thao tác ở đây. Không sử dụng thông tin bảo mật hay tài khoản ngân hàng thực tế.</p><footer><button className="users-button" onClick={onClose}>Đóng</button></footer></DemoDialog>
  if (dialog.type === 'review') return <DemoDialog title={`Rà soát #${t.id} — Bản mẫu`} closeLabel="Đóng hộp thoại" onClose={onClose}><p>{t.issue.summary}</p><p className="users-demo-note">Chỉ lưu ghi chú và trạng thái đã xem trong phiên hiện tại. Không thay đổi trạng thái giao dịch, số tiền hay kết quả đối soát trên hệ thống thực.</p><form className="users-form" noValidate onSubmit={event => { event.preventDefault(); if (note.trim().length < 5) return setError('Ghi chú minh họa phải có ít nhất 5 ký tự.'); onSaveReview({ note: note.trim(), reviewed }) }}><label>Ghi chú rà soát<input value={note} onChange={event => setNote(event.target.value)} maxLength={250} required /></label><label className="payments-review-check"><input type="checkbox" checked={reviewed} onChange={event => setReviewed(event.target.checked)} />Đã xem trong bản mẫu (không xác nhận đối soát)</label>{error && <p className="users-form-error" role="alert">{error}</p>}<footer><button type="button" className="users-button" onClick={onClose}>Giữ nguyên</button><button className="users-button primary">Lưu ghi chú minh họa</button></footer></form></DemoDialog>
  if (dialog.type === 'escrow') return <DemoDialog title="Thông tin ký quỹ — Bản mẫu" closeLabel="Đóng hộp thoại" onClose={onClose}><p>#{t.id} · {t.escrow}</p>{t.members.length ? <SplitSummary transaction={t} /> : <p>Giá trị giao dịch: {money(t.amount)}. Phương thức: {methodLabels[t.method]}.</p>}<p className="users-demo-note">Chỉ xem dữ liệu mẫu. Không có thao tác giữ tiền, giải ngân, hoàn tiền, rút tiền hoặc chuyển tiền.</p><footer><button className="users-button" onClick={onClose}>Đóng</button></footer></DemoDialog>
  if (dialog.type === 'refund') return <DemoDialog title="Bản ghi hoàn tiền có sẵn — Minh họa" closeLabel="Đóng hộp thoại" onClose={onClose}><dl className="payments-metadata">{[['Giao dịch mẫu', t.id], ['Tham chiếu ban đầu', t.refund.originalId], ['Số tiền mẫu', money(t.refund.amount)], ['Ngày ghi nhận', date(t.refund.date)], ['Lý do mẫu', t.refund.reason]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="users-demo-note">Đây là bản ghi đã có trong dữ liệu giả lập, không phải kết quả thực hiện hoàn tiền. Không gửi yêu cầu hoặc mô phỏng xử lý hoàn tiền.</p><footer><button className="users-button" onClick={onClose}>Đóng</button></footer></DemoDialog>
  if (dialog.type === 'user') return <DemoDialog title="Hồ sơ người dùng — Bản mẫu" closeLabel="Đóng hộp thoại" onClose={onClose}><div className="payments-user"><UserAvatar user={t.user} /><div><strong>{t.user.name}</strong><small>@{t.user.username} · {t.user.role}</small></div></div><p className="users-demo-note">Thông tin người dùng giả lập trong giao dịch #{t.id}; không tra cứu tài khoản thực tế.</p><footer><button className="users-button" onClick={onClose}>Đóng</button></footer></DemoDialog>
  return <DemoDialog title="Đơn đặt sân liên quan — Bản mẫu" closeLabel="Đóng hộp thoại" onClose={onClose}><h3>#{t.booking.id}</h3><p>{t.booking.facility} · {t.booking.court}</p><p>{date(t.booking.date)} · {t.booking.start} – {t.booking.end}</p><p>{t.booking.status}</p><p className="users-demo-note">Đơn minh họa riêng của trang thanh toán; không truy cập hoặc thay đổi đặt sân thực tế.</p><footer><button className="users-button" onClick={onClose}>Đóng</button></footer></DemoDialog>
}
