import { ChevronLeft, ChevronRight } from 'lucide-react'
import { UserAvatar } from '../Users/UserDetails.jsx'
import { TransactionStatus } from './TransactionDetails.jsx'
import { typeLabels, methodLabels, money, date, number } from './paymentData.js'

export default function TransactionTable({ transactions, detailId, onDetail, page, pageSize, onPage, onPageSize }) {
  const pages = Math.max(1, Math.ceil(transactions.length / pageSize)), current = Math.min(page, pages)
  const visible = transactions.slice((current - 1) * pageSize, current * pageSize)
  return <section className="payments-table-panel" aria-label="Danh sách giao dịch"><header><h2>Danh sách giao dịch <small>{number(transactions.length)} giao dịch mẫu</small></h2></header><div className="payments-table-scroll"><table><thead><tr>{['Mã giao dịch', 'Người dùng', 'Loại giao dịch', 'Tham chiếu', 'Số tiền', 'Trạng thái', 'Phương thức', 'Ngày / giờ'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{visible.map(t => <tr key={t.id} className={`${detailId === t.id ? 'is-selected' : ''} ${t.issue && !t.issue.reviewed ? 'has-issue' : ''}`} onClick={() => onDetail(t.id)}><td><button className="payments-id-button" onClick={() => onDetail(t.id)} aria-expanded={detailId === t.id}>#{t.id}</button>{t.issue && !t.issue.reviewed && <small className="payments-issue-tag">Cần rà soát</small>}</td><td><div className="payments-table-user"><UserAvatar user={t.user} /><strong>{t.user.name}</strong></div></td><td><span className={`payments-type ${t.type.toLowerCase()}`}>{typeLabels[t.type]}</span></td><td>{t.reference}</td><td><strong>{money(t.amount)}</strong></td><td><TransactionStatus status={t.status} /></td><td>{methodLabels[t.method]}</td><td>{date(t.createdDate)}<small>{t.createdTime}</small></td></tr>)}</tbody></table>{!visible.length && <p className="payments-empty">Không có giao dịch phù hợp. Hãy điều chỉnh hoặc đặt lại bộ lọc.</p>}</div><footer className="payments-pagination"><span>Hiển thị {transactions.length ? number((current - 1) * pageSize + 1) : 0}–{number(Math.min(current * pageSize, transactions.length))} / {number(transactions.length)} giao dịch mẫu</span><label>Số dòng mỗi trang<select value={pageSize} onChange={event => onPageSize(Number(event.target.value))}>{[5, 10, 15].map(size => <option key={size} value={size}>{size} dòng</option>)}</select></label><nav aria-label="Phân trang giao dịch"><button aria-label="Trang trước" disabled={current === 1} onClick={() => onPage(current - 1)}><ChevronLeft size={13} /></button>{Array.from({ length: pages }, (_, index) => index + 1).map(value => <button key={value} aria-label={`Trang ${value}`} aria-current={value === current ? 'page' : undefined} onClick={() => onPage(value)}>{value}</button>)}<button aria-label="Trang sau" disabled={current === pages} onClick={() => onPage(current + 1)}><ChevronRight size={13} /></button></nav></footer></section>
}
