import { ChevronLeft, ChevronRight } from 'lucide-react'
import StatusBadge from '../components/StatusBadge.jsx'
import { UserAvatar } from '../Users/UserDetails.jsx'
import { PaymentBadge } from './BookingDetails.jsx'
import { bookingStatusLabels, sportLabels, money, number, date, bookingTotal } from './bookingData.js'

export default function BookingTable({ bookings, selected, setSelected, detailId, onDetail, page, pageSize, onPage, onPageSize }) {
  const pages = Math.max(1, Math.ceil(bookings.length / pageSize))
  const currentPage = Math.min(page, pages)
  const visible = bookings.slice((currentPage - 1) * pageSize, currentPage * pageSize)
  const allSelected = visible.length > 0 && visible.every(booking => selected.includes(booking.id))
  const selectAll = () => setSelected(previous => allSelected ? previous.filter(id => !visible.some(booking => booking.id === id)) : [...new Set([...previous, ...visible.map(booking => booking.id)])])
  const toggle = id => setSelected(previous => previous.includes(id) ? previous.filter(item => item !== id) : [...previous, id])
  return <section className="bookings-table-panel" aria-label="Danh sách đơn đặt sân"><div className="bookings-table-scroll"><table><thead><tr><th><input type="checkbox" aria-label="Chọn tất cả đơn trên trang" disabled={!visible.length} checked={allSelected} onChange={selectAll} ref={node => { if (node) node.indeterminate = !allSelected && visible.some(booking => selected.includes(booking.id)) }} /></th>{['Mã đơn đặt sân', 'Người đặt', 'Cơ sở / sân', 'Môn thể thao', 'Ngày / giờ', 'Trạng thái', 'Thanh toán', 'Tổng tiền'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{visible.map(booking => <tr key={booking.id} className={detailId === booking.id ? 'is-selected' : ''} onClick={() => onDetail(booking.id)}><td onClick={event => event.stopPropagation()}><input type="checkbox" aria-label={`Chọn đơn ${booking.id}`} checked={selected.includes(booking.id)} onChange={() => toggle(booking.id)} /></td><td><button className="bookings-id-button" onClick={() => onDetail(booking.id)} aria-expanded={detailId === booking.id}>#{booking.id}</button><small>Đơn đặt sân</small></td><td><div className="bookings-table-player"><UserAvatar user={booking.player} /><div><strong>{booking.player.name}</strong><small>@{booking.player.username}</small></div></div></td><td><strong>{booking.venue.name}</strong><small>{booking.venue.court}</small></td><td><span className={`bookings-sport ${booking.venue.sport.toLowerCase()}`}>{sportLabels[booking.venue.sport]}</span></td><td>{date(booking.date)}<small>{booking.start} – {booking.end}</small></td><td><StatusBadge status={booking.status} label={bookingStatusLabels[booking.status]} /></td><td><PaymentBadge status={booking.payment} /></td><td><strong className="bookings-table-amount">{money(bookingTotal(booking))}</strong></td></tr>)}</tbody></table>{!visible.length && <p className="bookings-empty">Không có đơn đặt sân phù hợp. Hãy đặt lại hoặc điều chỉnh bộ lọc.</p>}</div><footer className="bookings-pagination"><span>Hiển thị {bookings.length ? number((currentPage - 1) * pageSize + 1) : 0}–{number(Math.min(currentPage * pageSize, bookings.length))} / {number(bookings.length)} đơn mẫu</span><label>Số dòng mỗi trang<select value={pageSize} onChange={event => onPageSize(Number(event.target.value))}>{[5, 10, 15].map(size => <option key={size} value={size}>{size} dòng</option>)}</select></label><nav aria-label="Phân trang đơn đặt sân"><button aria-label="Trang trước" disabled={currentPage === 1} onClick={() => onPage(currentPage - 1)}><ChevronLeft size={13} /></button>{Array.from({ length: pages }, (_, index) => index + 1).map(value => <button key={value} aria-label={`Trang ${value}`} aria-current={currentPage === value ? 'page' : undefined} onClick={() => onPage(value)}>{value}</button>)}<button aria-label="Trang sau" disabled={currentPage === pages} onClick={() => onPage(currentPage + 1)}><ChevronRight size={13} /></button></nav></footer></section>
}
